// <auto-generated />
using System;
using LunaChinese.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LunaChinese.Infrastructure.Migrations
{
    [DbContext(typeof(LunaChineseDbContext))]
    [Migration("20260913120430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LunaChinese.Infrastructure.Entity.AnalysisAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Alias");

                    b.HasIndex("CanonicalKey");

                    b.ToTable("Aliases", (string)null);
                });

            modelBuilder.Entity("LunaChinese.Infrastructure.Entity.CachedAnalysis", b =>
                {
                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CanonicalKey");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("LunaChinese.Infrastructure.Entity.AnalysisAlias", b =>
                {
                    b.HasOne("LunaChinese.Infrastructure.Entity.CachedAnalysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("CanonicalKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
